In [6]:
# importing dependencies
import pandas as pd
import numpy as np
import scipy as st
import matplotlib.pyplot as plt
import requests
import json
import csv

In [7]:
# Import CSV containing covid data from the year 2020. 
csv_path = "Resources/owid-covid-data.csv"
covid_data = pd.read_csv(csv_path)
covid_data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Resources/owid-covid-data.csv'

In [3]:
#Find data types in csv file
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3546 entries, 0 to 3545
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    3546 non-null   object
 1   continent                                   3378 non-null   object
 2   location                                    3546 non-null   object
 3   date                                        3546 non-null   object
 4   total_cases                                 3281 non-null   float64
 5   new_cases                                   3444 non-null   float64
 6   new_cases_smoothed                          3444 non-null   float64
 7   total_deaths                                3041 non-null   float64
 8   new_deaths                                  3444 non-null   float64
 9   new_deaths_smoothed                         3444 non-null   float64
 10  total_cases_per_million                     3281 non-null   float64
 11  new_cases_per_million                       3444 non-null   float64
 12  new_cases_smoothed_per_million              3444 non-null   float64
 13  total_deaths_per_million                    3041 non-null   float64
 14  new_deaths_per_million                      3444 non-null   float64
 15  new_deaths_smoothed_per_million             3444 non-null   float64
 16  reproduction_rate                           2144 non-null   float64
 17  icu_patients                                398 non-null    float64
 18  icu_patients_per_million                    398 non-null    float64
 19  hosp_patients                               413 non-null    float64
 20  hosp_patients_per_million                   413 non-null    float64
 21  weekly_icu_admissions                       97 non-null     float64
 22  weekly_icu_admissions_per_million           97 non-null     float64
 23  weekly_hosp_admissions                      237 non-null    float64
 24  weekly_hosp_admissions_per_million          237 non-null    float64
 25  total_tests                                 884 non-null    float64
 26  new_tests                                   813 non-null    float64
 27  total_tests_per_thousand                    884 non-null    float64
 28  new_tests_per_thousand                      813 non-null    float64
 29  new_tests_smoothed                          1097 non-null   float64
 30  new_tests_smoothed_per_thousand             1097 non-null   float64
 31  positive_rate                               1011 non-null   float64
 32  tests_per_case                              1002 non-null   float64
 33  tests_units                                 1137 non-null   object
 34  total_vaccinations                          780 non-null    float64
 35  people_vaccinated                           749 non-null    float64
 36  people_fully_vaccinated                     708 non-null    float64
 37  total_boosters                              470 non-null    float64
 38  new_vaccinations                            674 non-null    float64
 39  new_vaccinations_smoothed                   1940 non-null   float64
 40  total_vaccinations_per_hundred              780 non-null    float64
 41  people_vaccinated_per_hundred               749 non-null    float64
 42  people_fully_vaccinated_per_hundred         708 non-null    float64
 43  total_boosters_per_hundred                  470 non-null    float64
 44  new_vaccinations_smoothed_per_million       1940 non-null   float64
 45  new_people_vaccinated_smoothed              1939 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  1939 non-null   float64
 47  stringency_index                            1989 non-null   float64
 48  population_density                          3007 non-null   float64
 49  median_age                                  2797 non-null   float64
 50  aged_65_older                               2699 non-null   float64
 51  aged_70_older                               2769 non-null   float64
 52  gdp_per_capita                              2741 non-null   float64
 53  extreme_poverty                             1766 non-null   float64
 54  cardiovasc_death_rate                       2746 non-null   float64
 55  diabetes_prevalence                         2886 non-null   float64
 56  female_smokers                              2060 non-null   float64
 57  male_smokers                                2032 non-null   float64
 58  handwashing_facilities                      1345 non-null   float64
 59  hospital_beds_per_thousand                  2424 non-null   float64
 60  life_expectancy                             3259 non-null   float64
 61  human_development_index                     2662 non-null   float64
 62  population                                  3546 non-null   int64
 63  excess_mortality_cumulative_absolute        50 non-null     float64
 64  excess_mortality_cumulative                 50 non-null     float64
 65  excess_mortality                            50 non-null     float64
 66  excess_mortality_cumulative_per_million     50 non-null     float64
dtypes: float64(61), int64(1), object(5)
memory usage: 1.8+ MB

In [4]:
#Replace missing values with 0, to prevent any mathematical errors
covid_data_filled = covid_data.fillna(0)
covid_data_filled.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,01/04/2020,166.0,52.0,17.714,4.0,0.0,0.429,...,0.0,37.746,0.5,64.83,0.511,41128772,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,01/07/2020,31359.0,121.0,268.286,735.0,2.0,16.714,...,0.0,37.746,0.5,64.83,0.511,41128772,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,01/10/2020,39268.0,14.0,17.571,1458.0,0.0,1.714,...,0.0,37.746,0.5,64.83,0.511,41128772,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,01/01/2021,52513.0,183.0,131.143,2201.0,12.0,9.429,...,0.0,37.746,0.5,64.83,0.511,41128772,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,01/04/2021,56517.0,63.0,41.571,2489.0,5.0,3.143,...,0.0,37.746,0.5,64.83,0.511,41128772,0.0,0.0,0.0,0.0

In [5]:
# List of columns to keep
selected_columns = [
    'continent', 'location', 'date', 'total_cases_per_million', 'total_deaths_per_million',
    'hosp_patients_per_million', 'total_vaccinations_per_hundred',
    'median_age', 'aged_65_older', 'gdp_per_capita', 'extreme_poverty', 'diabetes_prevalence',
    'female_smokers', 'male_smokers', 'handwashing_facilities'
]

# Create a new DataFrame with only the selected columns
selected_df = covid_data_filled[selected_columns]

# Display the first few rows of the selected DataFrame
selected_df.head()

,continent,location,date,total_cases_per_million,total_deaths_per_million,hosp_patients_per_million,total_vaccinations_per_hundred,median_age,aged_65_older,gdp_per_capita,extreme_poverty,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities
0,Asia,Afghanistan,01/04/2020,4.036,0.097,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
1,Asia,Afghanistan,01/07/2020,762.459,17.871,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
2,Asia,Afghanistan,01/10/2020,954.757,35.450,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
3,Asia,Afghanistan,01/01/2021,1276.795,53.515,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
4,Asia,Afghanistan,01/04/2021,1374.148,60.517,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746

In [6]:
# Define the new column names
new_column_names = {
    'continent': 'Continent',
    'location': 'Location',
    'date': 'Date',
    'total_cases_per_million': 'Total_Cases_per_Million',
    'total_deaths_per_million': 'Total_Deaths_per_Million',
    'hosp_patients_per_million': 'Hosp_Patients_per_Million',
    'total_vaccinations_per_hundred': 'Total_Vaccinations_per_Hundred',
    'median_age': 'Median_Age',
    'aged_65_older': 'Aged_65_Older',
    'gdp_per_capita': 'GDP_per_Capita',
    'extreme_poverty': 'Extreme_Poverty',
    'diabetes_prevalence': 'Diabetes_Prevalence',
    'female_smokers': 'Female_Smokers',
    'male_smokers': 'Male_Smokers',
    'handwashing_facilities': 'Handwashing_Facilities'
}

# Rename the columns using the new_column_names dictionary
cleaned_covid_data = selected_df.rename(columns=new_column_names)

# Display the DataFrame with renamed columns
cleaned_covid_data.head(10)

,Continent,Location,Date,Total_Cases_per_Million,Total_Deaths_per_Million,Hosp_Patients_per_Million,Total_Vaccinations_per_Hundred,Median_Age,Aged_65_Older,GDP_per_Capita,Extreme_Poverty,Diabetes_Prevalence,Female_Smokers,Male_Smokers,Handwashing_Facilities
0,Asia,Afghanistan,01/04/2020,4.036,0.097,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
1,Asia,Afghanistan,01/07/2020,762.459,17.871,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
2,Asia,Afghanistan,01/10/2020,954.757,35.450,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
3,Asia,Afghanistan,01/01/2021,1276.795,53.515,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
4,Asia,Afghanistan,01/04/2021,1374.148,60.517,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
5,Asia,Afghanistan,01/07/2021,2922.917,120.645,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
6,Asia,Afghanistan,01/10/2021,3770.329,175.206,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
7,Asia,Afghanistan,01/01/2022,3843.027,178.853,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
8,Asia,Afghanistan,01/04/2022,4321.719,186.487,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746
9,Asia,Afghanistan,01/07/2022,4437.964,187.776,0.0,0.0,18.6,2.581,1803.987,0.0,9.59,0.0,0.0,37.746

In [11]:
csv_file_path = "Resources/cleaned_covid_data.csv"
cleaned_covid_data.to_csv(csv_file_path, index=False)